name: BRONTOSAURUS!
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b2a8d4b-c4ec-4388-8461-63be920bb599.png
layout_spectrum: 1
typography_spectrum: 0.07134
author:
  name: BRONTOSAURUS!
  email: hello@brontosaurus.la
  url: brontosaurus.la
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/524b213b-1444-4c56-b338-40d1de5a2bbf.svg
title: Ad Creative & Production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fea167'
    - '#8b8b8b'
    - '#d0d0d0'
  brandStrength: 0.625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
