typography_spectrum: 0.30225
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fea167'
    - '#8b8b8b'
    - '#d0d0d0'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0393
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: BRONTOSAURUS!
  email: hello@brontosaurus.la
  url: brontosaurus.la
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/524b213b-1444-4c56-b338-40d1de5a2bbf.svg
name: BRONTOSAURUS!
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b2a8d4b-c4ec-4388-8461-63be920bb599.png
title: A creative collaboratory.
purpose: []
