name: Brontosaurus
favicon: null
layout_spectrum: 0.5811089624185115
typography_spectrum: 0.524648126680404
title: A creative collaboratory.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fea167'
    - '#8b8b8b'
    - '#d0d0d0'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
