typography_spectrum: 0.30225
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fea167'
    - '#8b8b8b'
    - '#d0d0d0'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0393
analytics:
  google: null
  facebook: null
  twitter: null
name: Brontosaurus
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A creative collaboratory.
purpose: []
